language: node_js
node_js:
    - '10.5.0'
cache:
    yarn: true
    directories:
        - ~/.cache
install:
    - make install
script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make test; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; fi'
branches:
    only:
        - master
