language: node_js
node_js:
    - '10.5.0'
cache:
    yarn: true
    directories:
        - ~/.cache
install:
    - make install
branches:
    only:
        - master
script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make test; fi'
before-deploy:
    - make build
deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: packages/app/dist
    keep-history: true
    on:
        branch: master
