language: node_js
node_js:
    - '10.5.0'
cache:
    yarn: true
    directories:
        - ~/.cache
install:
    - make install
branches:
    only:
        - master
script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make test; fi'
deploy:
    provider: script
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    script: make deploy
    on:
        branch: master
